// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9Z4MFzIYaBZTF-GaZ9gDoDDRrbCTIHw',
    appId: '1:200814709460:web:4ec70e660aa8cf74da8941',
    messagingSenderId: '200814709460',
    projectId: 'irmanalyser-cb8e6',
    authDomain: 'irmanalyser-cb8e6.firebaseapp.com',
    storageBucket: 'irmanalyser-cb8e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl26DqmeCCdSPCH6VCnaiA2adlZv6tVgM',
    appId: '1:200814709460:android:2f892a50c92feef2da8941',
    messagingSenderId: '200814709460',
    projectId: 'irmanalyser-cb8e6',
    storageBucket: 'irmanalyser-cb8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2GvPz5_J3cRSrDQDe7LHsKVNPaSqp1U',
    appId: '1:200814709460:ios:df4cab386544b875da8941',
    messagingSenderId: '200814709460',
    projectId: 'irmanalyser-cb8e6',
    storageBucket: 'irmanalyser-cb8e6.firebasestorage.app',
    iosBundleId: 'com.example.heartmrianalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2GvPz5_J3cRSrDQDe7LHsKVNPaSqp1U',
    appId: '1:200814709460:ios:df4cab386544b875da8941',
    messagingSenderId: '200814709460',
    projectId: 'irmanalyser-cb8e6',
    storageBucket: 'irmanalyser-cb8e6.firebasestorage.app',
    iosBundleId: 'com.example.heartmrianalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb9Z4MFzIYaBZTF-GaZ9gDoDDRrbCTIHw',
    appId: '1:200814709460:web:64e6ffde9dd2ee0dda8941',
    messagingSenderId: '200814709460',
    projectId: 'irmanalyser-cb8e6',
    authDomain: 'irmanalyser-cb8e6.firebaseapp.com',
    storageBucket: 'irmanalyser-cb8e6.firebasestorage.app',
  );

}